[package]
name = "Game1"
version = "0.1.0"
edition = "2024"

[dependencies]
sdl2 = { version = "0.37", features = ["image"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
dirs = "5.0"
